server:
  port: 8000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13107354527
    url: jdbc:mysql://47.107.246.207/ISI?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.douyuehan.doubao: info
mybatis:
  type-aliases-package: com.isi.pojo
  # 指定 Mapper.xml 的位置
  mapper-locations: classpath:mapper/*Mapper.xml,classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 UserMapper.xml 中就可以不写实体类的全路径名
  configuration:
    map-underscore-to-camel-case: true